example.property: "I AM IN THE DEFAULT NEW2"
spring.jpa.database: "MYSQL"
spring.datasource.platform:  "mysql"
spring.jpa.show-sql: "true"
spring.database.driverClassName: "org.mysql.Driver"
spring.datasource.url: "jdbc:mysql://127.0.0.1:3306/eagle_eye_local"
spring.datasource.username: "root"
spring.datasource.password: "{cipher}33e41b07afe17cea8ed174bd84cc59bfe0739b10277974ebdef599eef8bda6a5"
spring.datasource.testWhileIdle: "true"
spring.datasource.validationQuery: "SELECT 1"
spring.jpa.properties.hibernate.dialect: "org.hibernate.dialect.MySQL5Dialect"
redis.server: "redis"
redis.port: "6379"
signing.key: "345345fsdfsf5345"
tung.key : "tung_key2"
